#!/usr/bin/env python3
# ugh. I just need some variable substitution; why is bash so shit?
import argparse
import os
import io
import socket
from typing import Iterator, Optional
import shlex
from subprocess import Popen, check_call, check_output, run, PIPE


# TODO could just pipe?
def send(payload: Iterator[bytes]) -> None:
    # TODO can we exec into it?
    # TODO ideally we want to iterate though output?
    pl = b'\n'.join(payload) # TODO FIXME
    r = run(['sendmail', '-t'], input=pl)
    r.check_returncode()


def scu(*args):
    return ['systemctl', '--user', *args]


def payload(*, to: str, unit: str, journalctl_args: Optional[str]) -> Iterator[bytes]:
    hostname = socket.gethostname()
    # TODO think about subject..
    yield f'''
To: {to}
From: systemd <root@{hostname}>
Subject: {unit}
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8
'''.lstrip().encode('utf8')

    # TODO shorter status?
    r = run(scu('status', '--lines', '0', unit), stdout=PIPE, stderr=PIPE)
    # status returns non-zero code if the unit failed, so need to ignore failures..
    # TODO check return code?
    yield r.stdout # TODO not sure which one should keep?

    # TODO make defensive and send everything in email?
    TS = check_output(scu('show', '-p', 'ActiveEnterTimestamp', '--value', unit)).decode('utf8').strip()

    # TODO shlex?? ugh
    jargs = [] if journalctl_args is None else journalctl_args.split()
    LCMD = ['journalctl', '--user', '-u', unit, '--since', TS, *jargs]
    yield ' '.join(shlex.quote(x) for x in LCMD).encode('utf8') # meh
    yield b''
    yield check_output(LCMD)


def main() -> None:
    from argparse import ArgumentParser
    p = ArgumentParser()
    p.add_argument('--to', required=True)
    p.add_argument('--unit', required=True)
    p.add_argument('--journalctl-args', default=None)
    args = p.parse_args()

    pl = payload(to=args.to, unit=args.unit, journalctl_args=args.journalctl_args)
    send(payload=pl)


if __name__ == '__main__':
   main()

# # eh. not very atomic..
# # TODO FIXME make sure that we get some warning if the mailer itself fails?
# # systemctl --user show --value -p InvocationID systemdtab-test.service
# # TODO indicate if it failed?
# # TODO suggest how to inspect logs, include tail or link??
# # TODO ugh!
