#!/bin/bash -eux

CMD="systemctl --user status --full $2"

set +e
STATUS="$($CMD)"
set -e

# TODO FIXME make sure that we get some warning if the mailer itself fails?
# systemctl --user show --value -p InvocationID systemdtab-test.service

# TODO indicate if it failed?
# TODO suggest how to inspect logs, include tail or link??
# TODO ugh!
sendmail -t <<ERRMAIL
To: $1
From: systemd <root@$HOSTNAME>
Subject: $2
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

$CMD

$STATUS
ERRMAIL
