version: 2


jobs:
  build_and_check:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: python3 -m pip install --user --upgrade pip
      - run: ./.ci/install-deps
      - run: python3 -m pip install --user -r requirements-dev.txt
      - run: python3 -m pip install --user -r requirements.txt
      - run: PATH=~/.local/bin:$PATH .ci/run


workflows:
  version: 2
  build_and_check:
    jobs:
      - build_and_check
