version: 2


jobs:
  build_and_check:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: python3 -m pip install --user --upgrade pip
        # FIXME ugh. doesn't look like systemd works on circle??
      - run: PATH=~/.local/bin:$PATH .ci/run -e mypy


workflows:
  version: 2
  build_and_check:
    jobs:
      - build_and_check
